services:
  postgres:
    image: registry.docker.ir/postgres:16.3-alpine
    container_name: postgres
    ports:
      - "5435:5432"
    environment:
        POSTGRES_DB: jaamebaade
        POSTGRES_USER: jaamebaade_server_user
        POSTGRES_PASSWORD: jaamebaade_server_password
    volumes:
        - ./postgres-data:/var/lib/postgresql/data